/* Generated By:JavaCC: Do not edit this line. Lexer1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Lexer1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int KEYWORD = 9;
  /** RegularExpression Id. */
  int DIGIT = 10;
  /** RegularExpression Id. */
  int LETTER = 11;
  /** RegularExpression Id. */
  int ID = 12;
  /** RegularExpression Id. */
  int INTLIT = 13;
  /** RegularExpression Id. */
  int STRLIT = 14;
  /** RegularExpression Id. */
  int OPERATOR = 15;
  /** RegularExpression Id. */
  int DELIMITER = 16;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int MULTILINECOMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"/*\"",
    "<token of kind 7>",
    "\"*/\"",
    "<KEYWORD>",
    "<DIGIT>",
    "<LETTER>",
    "<ID>",
    "<INTLIT>",
    "<STRLIT>",
    "<OPERATOR>",
    "<DELIMITER>",
  };

}
