#!/bin/sh

# Script for running miniJava compiler tests. 
# (For CS321 Language and Compiler Design, Portland State University.)
#
# Usage:
#   ./runp tst/test01.java  -- test a single program 
#   ./runp tst/test*.java   -- test all programs
#
# The script will compare your parser's output with a ref file (if exists),
# and save the diffs in a .diff file.
#

for i
do
	d=`dirname $i`
	f=`basename $i .ast`
	echo -n "$d/$f: "
	java Checker $d/$f.ast 2>$d/$f.err
	if [ -s $d/$f.err ]; then 
          if [ -r $d/$f.err.ref ]; then
            diff -w $d/$f.err $d/$f.err.ref > $d/$f.err.diff; 
            if [ -s $d/$f.err.diff ]; then 
              echo "differs from ref (see $f.err.diff)"; 
            else
	      rm $d/$f.err $d/$f.err.diff;
              echo "matches ref"; 
            fi
	  else
            echo "no ref to compare"; 
	    cat $d/$f.err
          fi
	else 
	  echo "passed static check"
        fi
done
exit 0

