/* Generated By:JavaCC: Do not edit this line. MjParser0Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MjParser0Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int INTLIT = 7;
  /** RegularExpression Id. */
  int ID = 8;
  /** RegularExpression Id. */
  int EXTID = 9;
  /** RegularExpression Id. */
  int LITERAL = 10;
  /** RegularExpression Id. */
  int BINOP = 11;
  /** RegularExpression Id. */
  int UNOP = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<DIGIT>",
    "<INTLIT>",
    "<ID>",
    "<EXTID>",
    "<LITERAL>",
    "<BINOP>",
    "<UNOP>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
  };

}
